#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Tk
Version  : 804.036
Release  : 13
URL      : https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Tk-804.036.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Tk-804.036.tar.gz
Summary  : 'Tk - a Graphical User Interface Toolkit'
Group    : Development/Tools
License  : BSL-1.0 Libpng MIT TCL Zlib
Requires: perl-Tk-bin = %{version}-%{release}
Requires: perl-Tk-license = %{version}-%{release}
Requires: perl-Tk-man = %{version}-%{release}
Requires: perl-Tk-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : libX11-dev
BuildRequires : libXft-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : pkgconfig(x11)
BuildRequires : zlib-dev

%description
The Tcl (Tool Command Language) provides a powerful platform for
creating integration applications that tie together diverse
applications, protocols, devices, and frameworks.  When paired with
the Tk toolkit, Tcl provides the fastest and most powerful way to
create GUI applications that run on PCs, Unix, and the Macintosh.  Tcl
can also be used for a variety of web-related tasks and for creating
powerful command languages for applications.

%package bin
Summary: bin components for the perl-Tk package.
Group: Binaries
Requires: perl-Tk-license = %{version}-%{release}

%description bin
bin components for the perl-Tk package.


%package dev
Summary: dev components for the perl-Tk package.
Group: Development
Requires: perl-Tk-bin = %{version}-%{release}
Provides: perl-Tk-devel = %{version}-%{release}
Requires: perl-Tk = %{version}-%{release}

%description dev
dev components for the perl-Tk package.


%package license
Summary: license components for the perl-Tk package.
Group: Default

%description license
license components for the perl-Tk package.


%package man
Summary: man components for the perl-Tk package.
Group: Default

%description man
man components for the perl-Tk package.


%package perl
Summary: perl components for the perl-Tk package.
Group: Default
Requires: perl-Tk = %{version}-%{release}

%description perl
perl components for the perl-Tk package.


%prep
%setup -q -n Tk-804.036
cd %{_builddir}/Tk-804.036

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Tk
cp %{_builddir}/Tk-804.036/COPYING %{buildroot}/usr/share/package-licenses/perl-Tk/d99b9243ab98c8a7b409deebd5640e409f9b0d76
cp %{_builddir}/Tk-804.036/PNG/libpng/LICENSE %{buildroot}/usr/share/package-licenses/perl-Tk/ccfc862ce3f3a6d1842310478a7bd888198e923b
cp %{_builddir}/Tk-804.036/PNG/libpng/contrib/gregbook/LICENSE %{buildroot}/usr/share/package-licenses/perl-Tk/f1d4c454846d4d2b3770e2060b609caa54dbbb62
cp %{_builddir}/Tk-804.036/PNG/zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/perl-Tk/892b34f7865d90a6f949f50d95e49625a10bc7f0
cp %{_builddir}/Tk-804.036/Tk/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/91fce7efca8de072356110dab258295d9ae44d7c
cp %{_builddir}/Tk-804.036/pTk/Tix.license %{buildroot}/usr/share/package-licenses/perl-Tk/d25b85218471584ea0c59a94af431d4c4c7d8111
cp %{_builddir}/Tk-804.036/pTk/license.html_lib %{buildroot}/usr/share/package-licenses/perl-Tk/35c54f7654d46ce14800fde8bbd3f871a0419005
cp %{_builddir}/Tk-804.036/pTk/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/23b9e2acbabd4339fc189b9b2600863bdd86cfa4
cp %{_builddir}/Tk-804.036/pTk/mTk/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/a189512b4fccdce241403af0089eef5bb7a3d742
cp %{_builddir}/Tk-804.036/pTk/mTk/tclWin/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/fb491b7d739e821b59203daaeff6bce1e2870ed9
cp %{_builddir}/Tk-804.036/pTk/mTk/unix/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/c4dea77b184ecc57378ecd4e017b213c9bc1712e
cp %{_builddir}/Tk-804.036/pTk/mTk/win/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/c4dea77b184ecc57378ecd4e017b213c9bc1712e
cp %{_builddir}/Tk-804.036/pTk/mTk/xlib/X11/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/c4dea77b184ecc57378ecd4e017b213c9bc1712e
cp %{_builddir}/Tk-804.036/pTk/mTk/xlib/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/c4dea77b184ecc57378ecd4e017b213c9bc1712e
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gedi
/usr/bin/ptked
/usr/bin/ptksh
/usr/bin/tkjpeg
/usr/bin/widget

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Tie::Watch.3
/usr/share/man/man3/Tk.3
/usr/share/man/man3/Tk::804delta.3
/usr/share/man/man3/Tk::Adjuster.3
/usr/share/man/man3/Tk::Animation.3
/usr/share/man/man3/Tk::Balloon.3
/usr/share/man/man3/Tk::Bitmap.3
/usr/share/man/man3/Tk::BrowseEntry.3
/usr/share/man/man3/Tk::Button.3
/usr/share/man/man3/Tk::Canvas.3
/usr/share/man/man3/Tk::Checkbutton.3
/usr/share/man/man3/Tk::Clipboard.3
/usr/share/man/man3/Tk::CmdLine.3
/usr/share/man/man3/Tk::ColorEditor.3
/usr/share/man/man3/Tk::Compound.3
/usr/share/man/man3/Tk::ConfigSpecs.3
/usr/share/man/man3/Tk::DItem.3
/usr/share/man/man3/Tk::Derived.3
/usr/share/man/man3/Tk::Dialog.3
/usr/share/man/man3/Tk::DialogBox.3
/usr/share/man/man3/Tk::DirTree.3
/usr/share/man/man3/Tk::DragDrop::Common.3
/usr/share/man/man3/Tk::DragDrop::SunConst.3
/usr/share/man/man3/Tk::DropSite.3
/usr/share/man/man3/Tk::Entry.3
/usr/share/man/man3/Tk::Error.3
/usr/share/man/man3/Tk::ErrorDialog.3
/usr/share/man/man3/Tk::Eventloop.3
/usr/share/man/man3/Tk::FBox.3
/usr/share/man/man3/Tk::FileSelect.3
/usr/share/man/man3/Tk::Font.3
/usr/share/man/man3/Tk::Frame.3
/usr/share/man/man3/Tk::HList.3
/usr/share/man/man3/Tk::IO.3
/usr/share/man/man3/Tk::IconList.3
/usr/share/man/man3/Tk::Image.3
/usr/share/man/man3/Tk::InputO.3
/usr/share/man/man3/Tk::Internals.3
/usr/share/man/man3/Tk::JPEG.3
/usr/share/man/man3/Tk::LabFrame.3
/usr/share/man/man3/Tk::Label.3
/usr/share/man/man3/Tk::Labelframe.3
/usr/share/man/man3/Tk::Listbox.3
/usr/share/man/man3/Tk::MainWindow.3
/usr/share/man/man3/Tk::Menu.3
/usr/share/man/man3/Tk::Menu::Item.3
/usr/share/man/man3/Tk::Menubutton.3
/usr/share/man/man3/Tk::Message.3
/usr/share/man/man3/Tk::MsgBox.3
/usr/share/man/man3/Tk::Mwm.3
/usr/share/man/man3/Tk::NoteBook.3
/usr/share/man/man3/Tk::Optionmenu.3
/usr/share/man/man3/Tk::PNG.3
/usr/share/man/man3/Tk::Pane.3
/usr/share/man/man3/Tk::Panedwindow.3
/usr/share/man/man3/Tk::Photo.3
/usr/share/man/man3/Tk::Pixmap.3
/usr/share/man/man3/Tk::Popup.3
/usr/share/man/man3/Tk::ProgressBar.3
/usr/share/man/man3/Tk::ROText.3
/usr/share/man/man3/Tk::Radiobutton.3
/usr/share/man/man3/Tk::Reindex.3
/usr/share/man/man3/Tk::Scale.3
/usr/share/man/man3/Tk::Scrollbar.3
/usr/share/man/man3/Tk::Scrolled.3
/usr/share/man/man3/Tk::Spinbox.3
/usr/share/man/man3/Tk::Submethods.3
/usr/share/man/man3/Tk::TList.3
/usr/share/man/man3/Tk::Table.3
/usr/share/man/man3/Tk::Tcl-perl.3
/usr/share/man/man3/Tk::Text.3
/usr/share/man/man3/Tk::TextUndo.3
/usr/share/man/man3/Tk::Tiler.3
/usr/share/man/man3/Tk::TixGrid.3
/usr/share/man/man3/Tk::Toplevel.3
/usr/share/man/man3/Tk::Trace.3
/usr/share/man/man3/Tk::Tree.3
/usr/share/man/man3/Tk::UserGuide.3
/usr/share/man/man3/Tk::Widget.3
/usr/share/man/man3/Tk::WidgetDemo.3
/usr/share/man/man3/Tk::WinPhoto.3
/usr/share/man/man3/Tk::Wm.3
/usr/share/man/man3/Tk::X.3
/usr/share/man/man3/Tk::X11Font.3
/usr/share/man/man3/Tk::Xrm.3
/usr/share/man/man3/Tk::after.3
/usr/share/man/man3/Tk::bind.3
/usr/share/man/man3/Tk::bindtags.3
/usr/share/man/man3/Tk::callbacks.3
/usr/share/man/man3/Tk::chooseColor.3
/usr/share/man/man3/Tk::chooseDirectory.3
/usr/share/man/man3/Tk::composite.3
/usr/share/man/man3/Tk::demos::widget_lib::slide.3
/usr/share/man/man3/Tk::demos::widget_lib::trace2.3
/usr/share/man/man3/Tk::event.3
/usr/share/man/man3/Tk::exit.3
/usr/share/man/man3/Tk::fileevent.3
/usr/share/man/man3/Tk::focus.3
/usr/share/man/man3/Tk::form.3
/usr/share/man/man3/Tk::getOpenFile.3
/usr/share/man/man3/Tk::getSaveFile.3
/usr/share/man/man3/Tk::grab.3
/usr/share/man/man3/Tk::grid.3
/usr/share/man/man3/Tk::mega.3
/usr/share/man/man3/Tk::messageBox.3
/usr/share/man/man3/Tk::option.3
/usr/share/man/man3/Tk::options.3
/usr/share/man/man3/Tk::overview.3
/usr/share/man/man3/Tk::pTk.3
/usr/share/man/man3/Tk::pack.3
/usr/share/man/man3/Tk::palette.3
/usr/share/man/man3/Tk::place.3
/usr/share/man/man3/Tk::selection.3
/usr/share/man/man3/Tk::send.3
/usr/share/man/man3/Tk::tixWm.3
/usr/share/man/man3/Tk::tkvars.3
/usr/share/man/man3/Tk::widgets.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Tk/23b9e2acbabd4339fc189b9b2600863bdd86cfa4
/usr/share/package-licenses/perl-Tk/35c54f7654d46ce14800fde8bbd3f871a0419005
/usr/share/package-licenses/perl-Tk/892b34f7865d90a6f949f50d95e49625a10bc7f0
/usr/share/package-licenses/perl-Tk/91fce7efca8de072356110dab258295d9ae44d7c
/usr/share/package-licenses/perl-Tk/a189512b4fccdce241403af0089eef5bb7a3d742
/usr/share/package-licenses/perl-Tk/c4dea77b184ecc57378ecd4e017b213c9bc1712e
/usr/share/package-licenses/perl-Tk/ccfc862ce3f3a6d1842310478a7bd888198e923b
/usr/share/package-licenses/perl-Tk/d25b85218471584ea0c59a94af431d4c4c7d8111
/usr/share/package-licenses/perl-Tk/d99b9243ab98c8a7b409deebd5640e409f9b0d76
/usr/share/package-licenses/perl-Tk/f1d4c454846d4d2b3770e2060b609caa54dbbb62
/usr/share/package-licenses/perl-Tk/fb491b7d739e821b59203daaeff6bce1e2870ed9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ptked.1
/usr/share/man/man1/ptksh.1
/usr/share/man/man1/tkjpeg.1
/usr/share/man/man1/widget.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tie/Watch.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/804delta.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Adjuster.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Adjuster.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/After.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Animation.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Animation.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Balloon.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Balloon.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Bitmap.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Bitmap.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/BrowseEntry.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/BrowseEntry.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Button.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Button.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Camel.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Canvas.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Canvas.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Checkbutton.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Checkbutton.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Clipboard.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Clipboard.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/CmdLine.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/CmdLine.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ColorDialog.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ColorEdit.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ColorEditor.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ColorEditor.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ColorSelect.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Compound.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Compound.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Config.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ConfigSpecs.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Configure.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Credits
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DItem.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Derived.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Derived.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Dialog.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Dialog.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DialogBox.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DialogBox.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DirTree.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DirTree.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Dirlist.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DragDrop.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DragDrop/Common.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DragDrop/Common.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DragDrop/LocalDrop.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DragDrop/Rect.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DragDrop/SunConst.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DragDrop/SunConst.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DragDrop/SunDrop.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DragDrop/SunSite.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DragDrop/XDNDDrop.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DragDrop/XDNDSite.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DropSite.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DropSite.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/DummyEncode.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/English.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Entry.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Entry.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Error.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ErrorDialog.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ErrorDialog.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Event.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Event/IO.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Eventloop.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/FBox.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/FBox.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/FileSelect.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/FileSelect.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/FloatEntry.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Font.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Font.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Frame.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Frame.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/HList.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/HList.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/IO.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/IO.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/IconList.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/IconList.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Image.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Image.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/InputO.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/InputO.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Internals.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ItemStyle.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/JPEG.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/LabEntry.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/LabFrame.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/LabFrame.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/LabRadio.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Label.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Label.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Labelframe.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Labelframe.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Listbox.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Listbox.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/MMtry.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/MMutil.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/MainWindow.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/MainWindow.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/MakeDepend.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Menu.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Menu.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Menu/Item.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Menu/Item.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Menubar.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Menubutton.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Menubutton.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Message.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Message.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/MsgBox.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/MsgBox.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Mwm.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Mwm.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/NBFrame.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/NoteBook.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/NoteBook.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Optionmenu.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Optionmenu.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/PNG.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Pane.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Panedwindow.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Panedwindow.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Photo.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Photo.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Pixmap.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Pixmap.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Popup.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Pretty.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ProgressBar.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/README.Adjust
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ROText.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ROText.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Radiobutton.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Radiobutton.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Region.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Reindex.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ReindexedROText.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ReindexedText.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Scale.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Scale.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Scrollbar.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Scrollbar.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Scrolled.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Spinbox.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Spinbox.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Stats.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Submethods.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Submethods.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/TList.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/TList.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Table.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Table.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Tcl-perl.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Text.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Text.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Text/Tag.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/TextEdit.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/TextList.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/TextUndo.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/TextUndo.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Tiler.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Tiler.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/TixGrid.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/TixGrid.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Tk.xbm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Tk.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/TkXSUB.def
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Toplevel.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Toplevel.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Trace.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Tree.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Tree.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/UserGuide.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Widget.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Widget.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/WidgetDemo.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/WinPhoto.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Wm.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Wm.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/X.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/X.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/X11Font.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/X11Font.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Xcamel.gif
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Xlib.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Xrm.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/Xrm.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/act_folder.xbm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/act_folder.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/after.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/anim.gif
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/arrowdownwin.xbm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/balArrow.xbm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/bind.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/bindtags.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/callbacks.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/cbxarrow.xbm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/chooseColor.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/chooseDirectory.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/composite.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/LabEnLabRad.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/QuitPB.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/QuitPBa.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/c.icon
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/cursor.cur
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/cursor.mask
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/cursor.xbm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/dir.icon
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/dir.mask
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/earth.gif
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/earthris.gif
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/face
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/flagdown
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/flagup
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/grey.25
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/grey.5
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/letters
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/mickey.gif
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/ned.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/noletters
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/page.icon
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/page.mask
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/pattern
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/images/teapot.ppm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/Ball.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/HList.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/HList2.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/Plot.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/WidgetDemo.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/arrows.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/balloon.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/bind.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/bitmaps.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/bounce.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/browseentry.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/browseentry2.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/button.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/check.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/choosedir.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/clrpick.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/colors.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/cscroll.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/ctext.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/dialog1.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/dialog2.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/dirtree.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/entry1.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/entry2.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/entry3.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/filebox.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/floor.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/form.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/form_mgr.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/hello.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/hscale.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/icon.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/image1.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/image2.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/items.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/keysyms.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/labelframe.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/labels.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/labframe.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/mega.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/menbut.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/menus.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/menus2.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/msgBox.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/notebook.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/paned1.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/paned2.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/photo1.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/photo2.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/plot.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/progress.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/puzzle.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/radio.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/ruler.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/sayings.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/search.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/showVars.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/slide.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/spin.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/states.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/style.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/texts.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/trace1.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/trace2.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/transtile.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/twind.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/unicodeout.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/virtevents1.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widget_lib/vscale.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widtrib/Gedi.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widtrib/TEMPLATE.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widtrib/Tiler.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widtrib/all.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widtrib/cursor.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widtrib/lib/npuz/Xcamel.npuz
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widtrib/npuz.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/demos/widtrib/plop.pl
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/event.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/exit.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/file.xbm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/file.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/fileevent.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/focus.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/folder.xbm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/folder.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/form.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/getOpenFile.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/getSaveFile.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/grab.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/grid.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/icon.gif
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/install.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/license.terms
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/mega.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/messageBox.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/openfile.xbm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/openfolder.xbm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/openfolder.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/option.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/options.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/overview.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/Lang.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/Lang.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/Lang.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/Lang_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/Tcl-pTk
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/Xlib.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/Xlib.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/Xlib.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/Xlib_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/compat/limits.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/compat/stdlib.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/compat/unistd.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/default.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/img.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/imgInt.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/imgInt.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/imgInt.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/imgInt_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/ks_names.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/mkVFunc
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/moredefs.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/port.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tcl.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tclDecls.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tclDecls.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tclDecls.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tclDecls_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tclIntDecls.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tclIntPlatDecls.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tclMath.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tclPlatDecls.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tix.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tix.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tix.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixBitmaps.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixDef.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixForm.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixGrData.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixGrid.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixHList.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixImgXpm.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixImgXpm.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixImgXpm.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixImgXpm_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixInt.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixInt.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixInt.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixInt_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixPort.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixTList.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixUnixInt.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tixUnixPort.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tix_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tk.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tk.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tk.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tk3d.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkButton.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkCanvas.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkCanvases.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkColor.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkConfig.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkDecls.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkDecls.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkDecls.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkDecls_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkEvent.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkEvent.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkEvent.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkEvent_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkFileFilter.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkFont.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkImgPhoto.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkImgPhoto.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkImgPhoto.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkImgPhoto_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkInitScript.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkInt.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkInt.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkInt.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkIntDecls.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkIntDecls.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkIntDecls.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkIntDecls_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkIntPlatDecls.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkIntPlatDecls.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkIntPlatDecls.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkIntPlatDecls_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkIntXlibDecls.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkIntXlibDecls.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkIntXlibDecls.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkIntXlibDecls_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkInt_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkMenu.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkMenubutton.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkOption.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkOption.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkOption.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkOption_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkPlatDecls.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkPlatDecls.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkPlatDecls.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkPlatDecls_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkPort.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkScale.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkScrollbar.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkSelect.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkText.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkUndo.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkUnixDefault.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkUnixInt.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkUnixPort.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkVMacro.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tkXrm.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pTk/tk_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/pack.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/palette.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/place.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/ppport.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/prolog.ps
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/selection.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/send.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/srcfile.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/textfile.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/tixWm.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/tkGlue.def
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/tkGlue.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/tkGlue.m
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/tkGlue.t
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/tkGlue_f.h
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/tkvars.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/tranicon.gif
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/typemap
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/vtab.def
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/widgets.pm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/widgets.pod
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/win.xbm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/winfolder.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/Tk/wintext.xpm
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/CancelRepeat.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Canvas/Canvas.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Clipboard/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Clipboard/getSelected.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Compound/Compound.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/EnterFocus.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Entry/Entry.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Error.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Event/Event.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/FirstMenu.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/FocusChildren.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/FocusOK.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Frame/AddScrollbars.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Frame/FindMenu.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Frame/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Frame/freeze_on_map.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Frame/label.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Frame/labelPack.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Frame/labelVariable.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Frame/packscrollbars.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Frame/queuePack.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Frame/sbset.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Frame/scrollbars.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/HList/HList.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/IO/IO.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/ImageNames.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/ImageTypes.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/InputO/InputO.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/JPEG/JPEG.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/AutoScan.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/BeginExtend.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/BeginSelect.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/BeginToggle.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/ButtonRelease_1.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/CLEAR.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/Cancel.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/Cntrl_End.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/Cntrl_Home.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/Cntrl_backslash.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/DELETE.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/DataExtend.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/EXISTS.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/EXTEND.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/ExtendUpDown.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/FETCH.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/FETCHSIZE.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/Listbox.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/Motion.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/POP.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/PUSH.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/SHIFT.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/SPLICE.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/STORE.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/SelectAll.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/SetList.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/TIEARRAY.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/TIESCALAR.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/UNSHIFT.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/UpDown.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/clipboardPaste.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/deleteSelected.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/getSelected.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Listbox/xyIndex.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Menubutton/Menubutton.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Mwm/Mwm.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/NBFrame/NBFrame.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/PNG/PNG.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Pixmap/Pixmap.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Receive.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/RepeatId.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scale/Activate.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scale/ButtonDown.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scale/ButtonUp.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scale/ControlPress.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scale/Drag.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scale/EndDrag.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scale/Enter.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scale/Increment.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scale/Leave.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scale/Scale.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scale/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/ButtonDown.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/ButtonUp.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/Drag.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/EndDrag.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/Enter.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/Leave.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/Motion.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/ScrlByPages.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/ScrlByUnits.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/ScrlToPos.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/ScrlTopBottom.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/Scrollbar.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/Select.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/StartDrag.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Scrollbar/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Selection.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/TList/TList.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Table/Create.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Table/Posn.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Table/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Table/see.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Table/totalColumns.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Table/totalRows.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Text/Text.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Text/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/TextEdit/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/TextUndo/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/TixGrid/TixGrid.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Tk.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Toplevel/FG_BindIn.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Toplevel/FG_BindOut.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Toplevel/FG_Create.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Toplevel/FG_Destroy.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Toplevel/FG_In.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Toplevel/FG_Out.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Toplevel/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/TraverseToMenu.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/ASkludge.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/AltKeyInDialog.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/AmpWidget.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/FindAltKeyTarget.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/MasterMenu.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/RestoreFocusGrab.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/SetAmpText.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/SetFocusGrab.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/UnderlineAmpersand.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/bindDump.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/clipboardKeysyms.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Widget/pathname.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/WinPhoto/WinPhoto.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Wm/AnchorAdjust.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Wm/FullScreen.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Wm/Popup.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Wm/Post.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Wm/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Wm/iconposition.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/X/X.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/X/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/Xlib/Xlib.so
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/autosplit.ix
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/break.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/focusFollowsMouse.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/focusNext.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/focusPrev.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/getEncoding.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/getNextFocus.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/getPrevFocus.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/interps.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/lsearch.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/pTk/extralibs.ld
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/tabFocus.al
/usr/lib/perl5/vendor_perl/5.34.0/x86_64-linux-thread-multi/auto/Tk/updateWidgets.al
