#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Tk
Version  : 804.036
Release  : 14
URL      : https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Tk-804.036.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Tk-804.036.tar.gz
Summary  : 'Tk - a Graphical User Interface Toolkit'
Group    : Development/Tools
License  : BSL-1.0 Libpng MIT TCL Zlib
Requires: perl-Tk-bin = %{version}-%{release}
Requires: perl-Tk-license = %{version}-%{release}
Requires: perl-Tk-man = %{version}-%{release}
Requires: perl-Tk-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : libX11-dev
BuildRequires : libXft-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : pkgconfig(x11)
BuildRequires : zlib-dev

%description
The Tcl (Tool Command Language) provides a powerful platform for
creating integration applications that tie together diverse
applications, protocols, devices, and frameworks.  When paired with
the Tk toolkit, Tcl provides the fastest and most powerful way to
create GUI applications that run on PCs, Unix, and the Macintosh.  Tcl
can also be used for a variety of web-related tasks and for creating
powerful command languages for applications.

%package bin
Summary: bin components for the perl-Tk package.
Group: Binaries
Requires: perl-Tk-license = %{version}-%{release}

%description bin
bin components for the perl-Tk package.


%package dev
Summary: dev components for the perl-Tk package.
Group: Development
Requires: perl-Tk-bin = %{version}-%{release}
Provides: perl-Tk-devel = %{version}-%{release}
Requires: perl-Tk = %{version}-%{release}

%description dev
dev components for the perl-Tk package.


%package license
Summary: license components for the perl-Tk package.
Group: Default

%description license
license components for the perl-Tk package.


%package man
Summary: man components for the perl-Tk package.
Group: Default

%description man
man components for the perl-Tk package.


%package perl
Summary: perl components for the perl-Tk package.
Group: Default
Requires: perl-Tk = %{version}-%{release}

%description perl
perl components for the perl-Tk package.


%prep
%setup -q -n Tk-804.036
cd %{_builddir}/Tk-804.036

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Tk
cp %{_builddir}/Tk-804.036/COPYING %{buildroot}/usr/share/package-licenses/perl-Tk/d99b9243ab98c8a7b409deebd5640e409f9b0d76
cp %{_builddir}/Tk-804.036/PNG/libpng/LICENSE %{buildroot}/usr/share/package-licenses/perl-Tk/ccfc862ce3f3a6d1842310478a7bd888198e923b
cp %{_builddir}/Tk-804.036/PNG/libpng/contrib/gregbook/LICENSE %{buildroot}/usr/share/package-licenses/perl-Tk/f1d4c454846d4d2b3770e2060b609caa54dbbb62
cp %{_builddir}/Tk-804.036/PNG/zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/perl-Tk/892b34f7865d90a6f949f50d95e49625a10bc7f0
cp %{_builddir}/Tk-804.036/Tk/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/91fce7efca8de072356110dab258295d9ae44d7c
cp %{_builddir}/Tk-804.036/pTk/Tix.license %{buildroot}/usr/share/package-licenses/perl-Tk/d25b85218471584ea0c59a94af431d4c4c7d8111
cp %{_builddir}/Tk-804.036/pTk/license.html_lib %{buildroot}/usr/share/package-licenses/perl-Tk/35c54f7654d46ce14800fde8bbd3f871a0419005
cp %{_builddir}/Tk-804.036/pTk/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/23b9e2acbabd4339fc189b9b2600863bdd86cfa4
cp %{_builddir}/Tk-804.036/pTk/mTk/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/a189512b4fccdce241403af0089eef5bb7a3d742
cp %{_builddir}/Tk-804.036/pTk/mTk/tclWin/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/fb491b7d739e821b59203daaeff6bce1e2870ed9
cp %{_builddir}/Tk-804.036/pTk/mTk/unix/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/c4dea77b184ecc57378ecd4e017b213c9bc1712e
cp %{_builddir}/Tk-804.036/pTk/mTk/win/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/c4dea77b184ecc57378ecd4e017b213c9bc1712e
cp %{_builddir}/Tk-804.036/pTk/mTk/xlib/X11/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/c4dea77b184ecc57378ecd4e017b213c9bc1712e
cp %{_builddir}/Tk-804.036/pTk/mTk/xlib/license.terms %{buildroot}/usr/share/package-licenses/perl-Tk/c4dea77b184ecc57378ecd4e017b213c9bc1712e
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gedi
/usr/bin/ptked
/usr/bin/ptksh
/usr/bin/tkjpeg
/usr/bin/widget

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Tie::Watch.3
/usr/share/man/man3/Tk.3
/usr/share/man/man3/Tk::804delta.3
/usr/share/man/man3/Tk::Adjuster.3
/usr/share/man/man3/Tk::Animation.3
/usr/share/man/man3/Tk::Balloon.3
/usr/share/man/man3/Tk::Bitmap.3
/usr/share/man/man3/Tk::BrowseEntry.3
/usr/share/man/man3/Tk::Button.3
/usr/share/man/man3/Tk::Canvas.3
/usr/share/man/man3/Tk::Checkbutton.3
/usr/share/man/man3/Tk::Clipboard.3
/usr/share/man/man3/Tk::CmdLine.3
/usr/share/man/man3/Tk::ColorEditor.3
/usr/share/man/man3/Tk::Compound.3
/usr/share/man/man3/Tk::ConfigSpecs.3
/usr/share/man/man3/Tk::DItem.3
/usr/share/man/man3/Tk::Derived.3
/usr/share/man/man3/Tk::Dialog.3
/usr/share/man/man3/Tk::DialogBox.3
/usr/share/man/man3/Tk::DirTree.3
/usr/share/man/man3/Tk::DragDrop::Common.3
/usr/share/man/man3/Tk::DragDrop::SunConst.3
/usr/share/man/man3/Tk::DropSite.3
/usr/share/man/man3/Tk::Entry.3
/usr/share/man/man3/Tk::Error.3
/usr/share/man/man3/Tk::ErrorDialog.3
/usr/share/man/man3/Tk::Eventloop.3
/usr/share/man/man3/Tk::FBox.3
/usr/share/man/man3/Tk::FileSelect.3
/usr/share/man/man3/Tk::Font.3
/usr/share/man/man3/Tk::Frame.3
/usr/share/man/man3/Tk::HList.3
/usr/share/man/man3/Tk::IO.3
/usr/share/man/man3/Tk::IconList.3
/usr/share/man/man3/Tk::Image.3
/usr/share/man/man3/Tk::InputO.3
/usr/share/man/man3/Tk::Internals.3
/usr/share/man/man3/Tk::JPEG.3
/usr/share/man/man3/Tk::LabFrame.3
/usr/share/man/man3/Tk::Label.3
/usr/share/man/man3/Tk::Labelframe.3
/usr/share/man/man3/Tk::Listbox.3
/usr/share/man/man3/Tk::MainWindow.3
/usr/share/man/man3/Tk::Menu.3
/usr/share/man/man3/Tk::Menu::Item.3
/usr/share/man/man3/Tk::Menubutton.3
/usr/share/man/man3/Tk::Message.3
/usr/share/man/man3/Tk::MsgBox.3
/usr/share/man/man3/Tk::Mwm.3
/usr/share/man/man3/Tk::NoteBook.3
/usr/share/man/man3/Tk::Optionmenu.3
/usr/share/man/man3/Tk::PNG.3
/usr/share/man/man3/Tk::Pane.3
/usr/share/man/man3/Tk::Panedwindow.3
/usr/share/man/man3/Tk::Photo.3
/usr/share/man/man3/Tk::Pixmap.3
/usr/share/man/man3/Tk::Popup.3
/usr/share/man/man3/Tk::ProgressBar.3
/usr/share/man/man3/Tk::ROText.3
/usr/share/man/man3/Tk::Radiobutton.3
/usr/share/man/man3/Tk::Reindex.3
/usr/share/man/man3/Tk::Scale.3
/usr/share/man/man3/Tk::Scrollbar.3
/usr/share/man/man3/Tk::Scrolled.3
/usr/share/man/man3/Tk::Spinbox.3
/usr/share/man/man3/Tk::Submethods.3
/usr/share/man/man3/Tk::TList.3
/usr/share/man/man3/Tk::Table.3
/usr/share/man/man3/Tk::Tcl-perl.3
/usr/share/man/man3/Tk::Text.3
/usr/share/man/man3/Tk::TextUndo.3
/usr/share/man/man3/Tk::Tiler.3
/usr/share/man/man3/Tk::TixGrid.3
/usr/share/man/man3/Tk::Toplevel.3
/usr/share/man/man3/Tk::Trace.3
/usr/share/man/man3/Tk::Tree.3
/usr/share/man/man3/Tk::UserGuide.3
/usr/share/man/man3/Tk::Widget.3
/usr/share/man/man3/Tk::WidgetDemo.3
/usr/share/man/man3/Tk::WinPhoto.3
/usr/share/man/man3/Tk::Wm.3
/usr/share/man/man3/Tk::X.3
/usr/share/man/man3/Tk::X11Font.3
/usr/share/man/man3/Tk::Xrm.3
/usr/share/man/man3/Tk::after.3
/usr/share/man/man3/Tk::bind.3
/usr/share/man/man3/Tk::bindtags.3
/usr/share/man/man3/Tk::callbacks.3
/usr/share/man/man3/Tk::chooseColor.3
/usr/share/man/man3/Tk::chooseDirectory.3
/usr/share/man/man3/Tk::composite.3
/usr/share/man/man3/Tk::demos::widget_lib::slide.3
/usr/share/man/man3/Tk::demos::widget_lib::trace2.3
/usr/share/man/man3/Tk::event.3
/usr/share/man/man3/Tk::exit.3
/usr/share/man/man3/Tk::fileevent.3
/usr/share/man/man3/Tk::focus.3
/usr/share/man/man3/Tk::form.3
/usr/share/man/man3/Tk::getOpenFile.3
/usr/share/man/man3/Tk::getSaveFile.3
/usr/share/man/man3/Tk::grab.3
/usr/share/man/man3/Tk::grid.3
/usr/share/man/man3/Tk::mega.3
/usr/share/man/man3/Tk::messageBox.3
/usr/share/man/man3/Tk::option.3
/usr/share/man/man3/Tk::options.3
/usr/share/man/man3/Tk::overview.3
/usr/share/man/man3/Tk::pTk.3
/usr/share/man/man3/Tk::pack.3
/usr/share/man/man3/Tk::palette.3
/usr/share/man/man3/Tk::place.3
/usr/share/man/man3/Tk::selection.3
/usr/share/man/man3/Tk::send.3
/usr/share/man/man3/Tk::tixWm.3
/usr/share/man/man3/Tk::tkvars.3
/usr/share/man/man3/Tk::widgets.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Tk/23b9e2acbabd4339fc189b9b2600863bdd86cfa4
/usr/share/package-licenses/perl-Tk/35c54f7654d46ce14800fde8bbd3f871a0419005
/usr/share/package-licenses/perl-Tk/892b34f7865d90a6f949f50d95e49625a10bc7f0
/usr/share/package-licenses/perl-Tk/91fce7efca8de072356110dab258295d9ae44d7c
/usr/share/package-licenses/perl-Tk/a189512b4fccdce241403af0089eef5bb7a3d742
/usr/share/package-licenses/perl-Tk/c4dea77b184ecc57378ecd4e017b213c9bc1712e
/usr/share/package-licenses/perl-Tk/ccfc862ce3f3a6d1842310478a7bd888198e923b
/usr/share/package-licenses/perl-Tk/d25b85218471584ea0c59a94af431d4c4c7d8111
/usr/share/package-licenses/perl-Tk/d99b9243ab98c8a7b409deebd5640e409f9b0d76
/usr/share/package-licenses/perl-Tk/f1d4c454846d4d2b3770e2060b609caa54dbbb62
/usr/share/package-licenses/perl-Tk/fb491b7d739e821b59203daaeff6bce1e2870ed9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ptked.1
/usr/share/man/man1/ptksh.1
/usr/share/man/man1/tkjpeg.1
/usr/share/man/man1/widget.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
